# Generated by Django 5.0.7 on 2024-08-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_bio',
            field=models.TextField(default=None, max_length=50, null=True),
        ),
    ]
