# Generated by Django 5.0.7 on 2024-07-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0003_blog_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='caption',
            field=models.TextField(),
        ),
    ]
